### ISSUE TITLE
Buffer size to be too large. 

### ISSUE THREAD

**Issue by franklupo** [douglasg14b/BetterConsoleTables#13]
Hi,
what does this mean?

> The new console window size would force the console buffer size to be too large. 
> Parameter name: width
> Actual value was 186

Best regards

**Comment by douglasg14b** [comment]
Hu,

That's a new one. It essentially means the console this was ran in has a width restriction smaller than the value the table tried to expand it to.

I believe I can fix this by checking for the max width of the console before attempting to resize.

**Comment by douglasg14b** [comment]
Also note that this means that your table is too wide for your console, and the console will start wrapping text, which will break the table's formatting.

**Comment by douglasg14b** [comment]
Update to v`1.1.1` when nuget finishes indexing. Should be resolved.

**Comment by franklupo** [comment]
Good. Is possible disable resize Windows?

**Comment by douglasg14b** [comment]
I suppose it could be, yeah. Can you make another issue as a request for this?

**Comment by douglasg14b** [comment]
@franklupo  I've added a `ExpandConsole` flag in the config.

Set this to false to disable expanding the window. You can find this on v 1.1.2 when it's indexed on nuget
