### ISSUE TITLE
Html output

### ISSUE THREAD

**Issue by franklupo** [douglasg14b/BetterConsoleTables#14]
Hi,
Is possible create output html?

Best regards

**Comment by douglasg14b** [comment]
I could be, yes.

This is something I'll take into consideration after I'm done with V2

**Comment by franklupo** [comment]
I,
when will release the V2?

Best regards

**Comment by douglasg14b** [comment]
No idea, I'm working on it when I have the time an energy away from my day job.

Also, to clarify, are you talking about an HTML output string? If so, that IS a bit out of scope of this project which is aimed at displaying tables in the console... 

Though I'd look deeper into it once I'm done with my current iteration.

**Comment by douglasg14b** [comment]
After mulling this over, this is not something that wilI will include in this library. If at some point in the future I think it's a good idea for an extensions lib, then I will add it.

HTML output is a grenade I'd rather not pull the pin on.
