### ISSUE TITLE
IndexOutOfRangeException when no rows were given

### ISSUE THREAD

**Issue by fubar-coder** [douglasg14b/BetterConsoleTables#15]
This is the stack trace:

```text
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BetterConsoleTables.Table.ToString(Int32[] columnLengths)
   at BetterConsoleTables.Table.ToString()
 ```

**Comment by douglasg14b** [comment]
Thanks for the report, I'll look into this at my next availability.

**Comment by douglasg14b** [comment]
This will be fixed in v2

For now make sure to add even a blank row, if that is too much of a bother I can make a change on this branch.

**Comment by fubar-coder** [comment]
I worked around this problem by writing a message that there's no data available (and this doesn't write a table).

**Comment by douglasg14b** [comment]
closing as reoslved
