### ISSUE TITLE
ForegroundColor seems to break the table.

### ISSUE THREAD

**Issue by ViezeVingertjes** [douglasg14b/BetterConsoleTables#28]
For some reason, when i try to use the ForegroundColor, it breaks the table. Anyone has had the same issue and possibly found a fix?

![image](https://user-images.githubusercontent.com/10432760/175766280-b1bee2de-c723-4a90-a3e3-7c936469725e.png)

**Comment by douglasg14b** [comment]
Please post your code.

Likely a duplicate of #24 

Please use the formatting extensions for the column, or `HasInnerFormatting()`. You can find examples in the linked issue.
