### ISSUE TITLE
Cant find ns for Column

### ISSUE THREAD

**Issue by krzm** [douglasg14b/BetterConsoleTables#30]
I added nuget and try to use Column type
Cant find ns
Shame, i wanted to use this lib

**Comment by douglasg14b** [comment]
Please provide additional information, such as a code example, the full error message...etc

It's not possible to help you otherwise.

**Comment by krzm** [comment]
Yes, hello
[better-console-tables-wrapper.zip](https://github.com/douglasg14b/BetterConsoleTables/files/9125767/better-console-tables-wrapper.zip)
I atached repo.
I want to wrapp lib to learn to use it, and produce some standard way of it.
I add test app. Here is proj file
```
<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Better.Console.Tables.Wrapper\Better.Console.Tables.Wrapper.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BetterConsoleTables" Version="1.1.3" />
    </ItemGroup>

</Project>
```
I copy first method from ur example
```
using BetterConsoleTables;
using AConsole = System.Console;

namespace Better.Console.Tables.TestApp;

internal class Program
{
    private static void Main(string[] args)
    {
        NoRows();
        AConsole.WriteLine("Complete");
        AConsole.ReadLine();
    }

    private static void NoRows()
    {
        Column[] headers = new[]
        {
            new Column("Left"),
            new Column("Left Header"),
            new Column("Right Header"),
        };


        var table = new Table(headers);
        table.Config = TableConfig.Unicode();

        var ret = table.ToString();

        AConsole.Write(ret);
    }
}
```
This is my problem
`The type or namespace name 'Column' could not be found (are you missing a using directive or an assembly reference?`

Now there was some crappy warrnings that nuget is not stamped by nuget,org or whatever, but after admin mode it was gone when installing it.

**Comment by douglasg14b** [comment]
The problem is you have version 1 installed from nuget, and are trying to use the v2 api.

The readme for this repo has examples of how to use v1 of this library. If you want to use v2, you will need to install the beta nuget package.

**Comment by krzm** [comment]
Thank you for information.
I will try to use it when i go back to this task.
