### ISSUE TITLE
[Feature Request] Add rendering to image

### ISSUE THREAD

**Issue by theelderwand** [douglasg14b/BetterConsoleTables#32]
Can we have an option where we can render the entire table into an image like PNG ?

`table.ToImage(ImageFormat.Png)`

**Comment by douglasg14b** [comment]
This would be pretty out of scope for this lib, and involves a lot of APIs that may be different depending on the platform. And in general is not a can of worms I wish to open.

If this is something you want to develop feel free to start figuring it out on a branch, and open a draft PR, and we can work on it together.
