### ISSUE TITLE
Does not work on linux

### ISSUE THREAD

**Issue by bilal-fazlani** [douglasg14b/BetterConsoleTables#4]
```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
23:43:06.176    at System.ConsolePal.set_WindowWidth(Int32 value)
23:43:06.176    at BetterConsoleTables.Table.PadRow(String row)
23:43:06.176    at BetterConsoleTables.Table.ToString(Int32[] columnLengths)
```

**Comment by douglasg14b** [comment]
This has been resolved in the most recent version, I need to update the nuget package with a new release so it's available.

For now we can't set the WindowWidth on Mac or Linux with .net core.

**Comment by douglasg14b** [comment]
Package has been updated, please update your install to `1.0.1`.

**Comment by bilal-fazlani** [comment]
`Unfixable` ? does that mean 1.0.1 doesn't work linux?

**Comment by douglasg14b** [comment]
It means the underlying issue is not resolvable as the .net core 2 api does not support resizing the window on linux or mac.

There is a check in there that just skips window resizing if it's not the correct environment, so `1.0.1` should work fine sans window resizing.
