### ISSUE TITLE
Null value are not handled

### ISSUE THREAD

**Issue by gregsdennis** [douglasg14b/BetterConsoleTables#7]
If I am building a table from a collection of objects, and any of the property values are null, a NullReferenceException is thrown.  I should get `(null)` or something similar in the output.

**Comment by douglasg14b** [comment]
I'll fix this soon! 

Thanks for the report.

**Comment by douglasg14b** [comment]
THis should be resolved in `1.0.3` which has been published to nuget. Please let m know if you find any other issues.

**Comment by douglasg14b** [comment]
Closing as I have not heard back, and this issue has been resolved.

**Comment by gregsdennis** [comment]
Oh, sorry. Must have missed the notification. I'll update in my project and let you know. Thanks.
