### ISSUE TITLE
Config.UnicodeAlt(); not working

### ISSUE THREAD

**Issue by Zanga1** [douglasg14b/BetterConsoleTables#8]
.Config = Config.UnicodeAlt(); Not working

I needed to delete that line and add:
table.Config = TableConfiguration.UnicodeAlt();

Should be changed in documentation

thank you

**Comment by douglasg14b** [comment]
Thanks! 

I'll look into this

**Comment by douglasg14b** [comment]
@Zanga1 

This is because the `Config` class was removed for `TableConfiguration` to avoid using such a general name, which causes conflicts with other libraries.

I'll update the documentation.
