### ISSUE TITLE
Column align to right

### ISSUE THREAD

**Issue by franklupo** [douglasg14b/BetterConsoleTables#9]
Hi,
wonderful job. Is it possible to specify in ToString if the column is aligned to the right?

Best regards

**Comment by davidnmbond** [comment]
We'd also like to right align numbers.  Please do add this feature!

**Comment by douglasg14b** [comment]
Oh hey, I completely forgot about this!

For now alignment will be on a per-column basis, and will pad based on the max column width. Meaning if the column width is the same as number of characters in that row, they won't appear right-aligned. 

Thoughts?

**Comment by douglasg14b** [comment]
@davidnmbond  @franklupo I have added support for aligning both the headers and the rows to `Left`, `Right`, or `Center`. This is available under the `1.1.0` nuget package that still indexing.

**Comment by franklupo** [comment]
Hi,
the table.AddColumn(...) not working with align but in constructor yes.

Best regards

**Comment by douglasg14b** [comment]
@franklupo Can you paste a brief repro for me?

This is working for me:

```cs
    Table table = new Table("Left");
    table.AddColumn("Left Header", Alignment.Right)
        .AddColumn("Right Header", Alignment.Center, Alignment.Right)
        .AddRow("1", "2", "3")
        .AddRow("Short", "item", "Here")
        .AddRow("Longer items go here", "Right Contents", "Centered Contents")
        .Config = TableConfiguration.MySqlSimple();

    Console.Write(table.ToString());
```
